---

spring:
  rabbitmq:
      host: rabbitmq
      username: guest
      password: guest
      port: 61613
  jpa:
      database: POSTGRESQL
      show-sql: true
      hibernate:
        ddl-auto: validate
  datasource:
      url: jdbc:postgresql://db:5432/database?
      username: admin
      password: admin
      driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: redis
      port: 6379

