version: "3"

services:
  postgres:
    container_name: 'java-postgres'
    environment:
      - 'POSTGRES_PASSWORD=admin'
      - 'POSTGRES_USER=admin'
      - 'POSTGRES_DB=database'
    image: postgres:16.2-bullseye

  app:
    build: ./
    container_name: 'java-app'
    ports:
      - 80:8080
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres/database?



