---

spring:
    rabbitmq:
      host: localhost
      username: guest
      password: guest
    jpa:
      database: POSTGRESQL
      show-sql: true
      hibernate:
        ddl-auto: create
    datasource:
      url: jdbc:postgresql://localhost:5432/database?
      username: admin
      password: admin
      driver-class-name: org.postgresql.Driver
