---

spring:
    rabbitmq:
      host: localhost
      username: guest
      password: guest
#      port: 5672
    jpa:
      database: POSTGRESQL
      show-sql: true
      hibernate:
        ddl-auto: update
    datasource:
      url: jdbc:postgresql://localhost:5432/database
      username: postgres
      password: 1
      driver-class-name: org.postgresql.Driver
